# 异常处理

​		在程序设计和运行的过程中，发生错误是不可避免的。为此，Java 提供了异常处理机制来帮助程序员检查可能出现的错误，以保证程序的可读性和可维护性。

​		Java 将异常封装到一个类中，出现错误时就会拋出异常。本章介绍异常处理的概念、异常处理语句，以及自定义异常等内容。

​		生活中的异常例子：很多事件并非总是按照人们自己设计意愿顺利发展的，经常出现这样那样的异常情况。例如： 你计划周末郊游，计划从家里出发→到达目的→游泳→烧烤→回家。但天有不测风云，当你准备烧烤时候突然天降大雨，只能终止郊游提前回家。“天降大雨”是一种异常情况，你的计划应该考虑到这样的情况，并且应该有处理这种异常的预案。

​		异常概念：**异常（exception）是在运行程序时产生的一种异常情况**，已经成为了衡量一门语言是否成熟的标准之一。

## 异常简介

​		[Java](http://c.biancheng.net/java/) 中的异常又称为例外，是一个在程序执行期间发生的事件，它中断正在执行程序的正常指令流。为了能够及时有效地处理程序中的运行错误，必须使用异常类，这可以让程序具有极好的容错性且更加健壮。 

​		在 Java 中一个异常的产生，主要有如下三种原因：

* Java 内部错误发生异常，Java 虚拟机产生的异常。
* 编写的程序代码中的错误所产生的异常，例如空指针异常、数组越界异常等。
* 通过 throw 语句手动生成的异常，一般用来告知该方法的调用者一些必要信息。

**例子一：**允许用户输入 1~3 以内的整数，其他情况提示输入错误。

```java
public static void main(String[] args) {
    System.out.println("请输入您的选择：（1~3 之间的整数）");
    Scanner input = new Scanner(System.in);
    int num = input.nextInt();
    switch (num) {
    case 1:
        System.out.println("one");
        break;
    case 2:
        System.out.println("two");
        break;
    case 3:
        System.out.println("three");
        break;
    default:
        System.out.println("error");
        break;
    }
}
```

​		正常情况下，用户会按照系统的提示输入 1~3 之间的数字。但是，如果用户没有按要求进行输入，例如输入了一个字母“a”，则程序在运行时将会发生异常，运行结果如下所示。

```java
请输入您的选择：（1~3 之间的整数）
a
Exception in thread "main" java.util.InputMismatchException
	at java.util.Scanner.throwFor(Scanner.java:864)
```

## 异常类型

​		在 Java 中所有异常类型都是内置类 java.lang.Throwable 类的子类，即 Throwable 位于异常类层次结构的顶层。Throwable 类下有两个异常分支 Exception 和 Error，如下图所示。

![img](http://c.biancheng.net/uploads/allimg/181023/3-1Q0231H424V1.jpg)



​		Throwable 类是所有异常和错误的超类，下面有 Error 和 Exception 两个子类分别表示错误（Error我们现阶段处理不了）和异常。其中异常类 Exception 又分为运行时异常和非运行时异常，这两种异常有很大的区别，也称为不检查异常（Unchecked Exception）和检查异常（Checked Exception）。

- Exception 类用于用户程序可能出现的异常情况，它也是用来创建自定义异常类型类的类。
- Error 定义了在通常环境下不希望被程序捕获的异常。一般指的是 JVM 错误，如堆栈溢出。

​			

​		**运行时异常和非运行时异常：**

* 运行时异常都是 RuntimeException 类及其子类异常，如 NullPointerException、IndexOutOfBoundsException 等，这些异常是不检查异常，程序中可以选择捕获处理，也可以不处理。这些异常一般由程序逻辑错误引起，程序应该从逻辑角度尽可能避免这类异常的发生。

* 非运行时异常是指 RuntimeException 以外的异常，类型上都属于 Exception 类及其子类。从程序语法角度讲是必须进行处理的异常，如果不处理，程序就不能编译通过。如 IOException、ClassNotFoundException 等以及用户自定义的 Exception 异常（一般情况下不自定义检查异常）。



**Java中常见运行时异常**

| 异常类型                      | 说明                                                  |
| ----------------------------- | ----------------------------------------------------- |
| ArithmeticException           | 算术错误异常，如以零做除数                            |
| ArraylndexOutOfBoundException | 数组索引越界                                          |
| ArrayStoreException           | 向类型不兼容的数组元素赋值                            |
| ClassCastException            | 类型转换异常                                          |
| IllegalArgumentException      | 使用非法实参调用方法                                  |
| lIIegalStateException         | 环境或应用程序处于不正确的状态                        |
| lIIegalThreadStateException   | 被请求的操作与当前线程状态不兼容                      |
| IndexOutOfBoundsException     | 某种类型的索引越界                                    |
| NullPointerException          | 尝试访问 null 对象成员，空指针异常                    |
| NegativeArraySizeException    | 再负数范围内创建的数组                                |
| NumberFormatException         | 数字转化格式异常，比如字符串到 float 型数字的转换无效 |
| TypeNotPresentException       | 类型未找到                                            |



**Java常见非运行时异常**

| 异常类型                     | 说明                       |
| ---------------------------- | -------------------------- |
| ClassNotFoundException       | 没有找到类                 |
| IllegalAccessException       | 访问类被拒绝               |
| InstantiationException       | 试图创建抽象类或接口的对象 |
| InterruptedException         | 线程被另一个线程中断       |
| NoSuchFieldException         | 请求的域不存在             |
| NoSuchMethodException        | 请求的方法不存在           |
| ReflectiveOperationException | 与反射有关的异常的超类     |



# Error和Exception的异同

​		Error（错误）和 Exception（异常）都是 java.lang.Throwable 类的子类，在 [Java](http://c.biancheng.net/java/) 代码中只有继承了 Throwable 类的实例才能被 throw 或者 catch。

​		Exception 和 Error 体现了 Java 平台设计者对不同异常情况的分类，Exception 是程序正常运行过程中可以预料到的意外情况，并且应该被开发者捕获，进行相应的处理。Error 是指正常情况下不大可能出现的情况，绝大部分的 Error 都会导致程序处于非正常、不可恢复状态。所以不需要被开发者捕获。

（1）运行时异常（RuntimeException）：

- NullPropagation：空指针异常；
- ClassCastException：类型强制转换异常
- IllegalArgumentException：传递非法参数异常
- IndexOutOfBoundsException：下标越界异常
- NumberFormatException：数字格式异常



（2）非运行时异常：

- ClassNotFoundException：找不到指定 class 的异常
- IOException：IO 操作异常


（3）错误（Error）：

- NoClassDefFoundError：找不到 class 定义异常
- StackOverflowError：深递归导致栈被耗尽而抛出的异常
- OutOfMemoryError：内存溢出异常

**例子一：**Java 堆栈溢出错误示例

```java
public static void main(String[] args) {
    test(5);

}
public static void test(int i) {
    if (i == 0) {
        return;
    } else {
        test(i++);
    }
}
```

运行结果如下：StackOverflowError(栈溢出错误)

```java
Exception in thread "main" java.lang.StackOverflowError
	at com.ambow.DemoException.T01.test(T01.java:14)
	at com.ambow.DemoException.T01.test(T01.java:14)
	at com.ambow.DemoException.T01.test(T01.java:14)
```



## 处理异常

​		Java的异常处理通过 5 个关键字来实现：try、catch、throw、throws 和 finally。try catch 语句用于捕获并处理异常，finally 语句用于在任何情况下（除特殊情况外）都必须执行的代码，throw 语句用于拋出异常，throws 语句用于声明可能会出现的异常。

​		Java 的异常处理机制提供了一种结构性和控制性的方式来处理程序执行期间发生的事件。异常处理的机制如下：

- 在方法中用 try catch 语句捕获并处理异常，catch 语句可以有多个，用来匹配多个异常。
- 对于处理不了的异常或者要转型的异常，在方法的声明处通过 throws 语句拋出异常，即由上层的调用方法来处理。

​		以下代码是异常处理程序的完整基本结构：

```java
try {
    逻辑程序块
} catch(ExceptionType1 e) {
    处理代码块1
} catch (ExceptionType2 e) {
    处理代码块2
    throw(e);    // 再抛出这个"异常"
} finally {		// 可省略
    释放资源代码块
}
```

​		

​		 Java 中通常采用 **try catch** 语句来捕获异常并处理。语法格式如下

```java
try {
    // 可能发生异常的语句
} catch(ExceptionType e) {
    // 处理异常语句
}
```

​		在以上语法中，把可能引发异常的语句封装在 try 语句块中，用以捕获可能发生的异常。catch 后的`( )`里放匹配的异常类，指明 catch 语句可以处理的异常类型，发生异常时产生异常类的实例化对象。

​		如果 try 语句块中发生异常，那么一个相应的异常对象就会被拋出，然后 catch 语句就会依据所拋出异常对象的类型进行捕获，并处理。处理之后，程序会跳过 try 语句块中剩余的语句，转到 catch 语句块后面的第一条语句开始执行。

​		如果 try 语句块中没有异常发生，那么 try 块正常结束，后面的 catch 语句块被跳过，程序将从 catch 语句块后的第一条语句开始执行。

注		意：try...catch 与 if...else 不一样，try 后面的花括号`{ }`不可以省略，即使 try 块里只有一行代码，也不可省略这个花括号。与之类似的是，catch 块后的花括号`{ }`也不可以省略。另外，try 块里声明的变量只是代码块内的局部变量，它只在 try 块内有效，其它地方不能访问该变量。

​		**例子一：**编写一个录入学生姓名、年龄和性别的程序，要求能捕捉年龄不为数字时的异常。在这里使用 try catch 语句来实现，具体代码如下：

```java
public static void main(String[] args) {
    Scanner scanner = new Scanner(System.in);
    System.out.println("---------学生信息录入---------------");
    String name = ""; // 获取学生姓名
    int age = 0; // 获取学生年龄
    String sex = ""; // 获取学生性别
    try {
        System.out.println("请输入学生姓名：");
        name = scanner.next();
        System.out.println("请输入学生年龄：");
        age = scanner.nextInt();
        System.out.println("请输入学生性别：");
        sex = scanner.next();
    } catch (Exception e) {
        e.printStackTrace();
        System.out.println("输入有误！");
    }
    System.out.println("姓名：" + name);
    System.out.println("年龄：" + age);
}
```

​		上述代码在 main() 方法中使用 try catch 语句来捕获异常，将可能发生异常的**age = scanner.nextlnt();**代码放在了 try 块中，在 catch 语句中指定捕获的异常类型为 Exception，并调用异常对象的 printStackTrace() 方法输出异常信息。运行结果如下所示。

```java
---------学生信息录入---------------
请输入学生姓名：
李白
请输入学生年龄：
110a
java.util.InputMismatchException
	at java.util.Scanner.throwFor(Scanner.java:864)
	at java.util.Scanner.next(Scanner.java:1485)
	at java.util.Scanner.nextInt(Scanner.java:2117)
	at java.util.Scanner.nextInt(Scanner.java:2076)
	at com.ambow.DemoException.T01.main(T01.java:16)
输入有误！
姓名：李白
年龄：0
```



































































